FROM golang:1.15.7 AS base

ENV PORT 8000
ENV HEROKU_DATABASE_URL ''

RUN apt-get update
RUN apt-get install -y python3 python3-pip

RUN go get -u github.com/silenceper/gowatch
RUN pip3 install youtube_dl

COPY . /app
WORKDIR /app

RUN go mod tidy

CMD make run