FROM golang:1.16.4 AS base

ENV PORT 8000
ENV DATABASE_URL 'lalala'
ENV GO111MODULE on

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip3 install youtube_dl

RUN go get -u github.com/silenceper/gowatch

COPY . /app
WORKDIR /app

RUN go mod tidy

CMD gowatch -p cmd/app/main.go -o main