services:
    back:
        build:
            context: .
            dockerfile: Dockerfile.back
        environment:
            - PORT=${PORT}
            - DATABASE_URL=${DATABASE_URL}
        ports:
            - "8000:8000"
            - "8080:8080"
        volumes:
            - .:/app
            - front_build:/app/web/front/build
    front:
        build:
            context: .
            dockerfile: Dockerfile.front
        volumes:
            - .:/app
            - node_modules:/app/web/front/node_modules
            - front_build:/app/web/front/build
volumes:
    node_modules:
    front_build: