services:
    back:
        build:
            context: .
            dockerfile: Dockerfile.back
        environment:
            - PORT
            - DATABASE_URL
        ports:
            - "8000:8000"
        volumes:
            - .:/app
    front:
        build:
            context: .
            dockerfile: Dockerfile.front
        volumes:
            - .:/app
            - node_modules:/app/web/front/node_modules
volumes:
    node_modules: